config/routes.rb
Rails.application.routes.draw do
  root :to => 'stories#index'

  resources :stories do
    resources :contributions
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contribution.rb
class Contribution < ActiveRecord::Base
  belongs_to :story
  default_scope { order ("id ASC")}

  validates :sentence, :presence => true
  validates :sentence, length: { minimum: 1, maximum: 120 }
  validates :user, :presence => true


end

app/models/story.rb
class Story < ActiveRecord::Base
  has_many :contributions
  default_scope { order ("name ASC")}
  validates :name, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contributions_controller.rb
class ContributionsController < ApplicationController
  def new
    @story = Story.find(params[:story_id])
    @contribution = @story.contributions.new
    @num = rand(5)
    @img_url = "story_images/#@num.jpg"
  end

  def create
    @story = Story.find(params[:story_id])
    @contribution = @story.contributions.new(contribution_params)
    @img_url = "story_images/#@num.jpg"
    flash[:notice] = "Sentence successfully added!"
    if @contribution.save
      redirect_to story_path(@contribution.story)
    else
      render :new
    end
  end

  def show
    @story = Story.find(params[:story_id])
    @contribution = Contribution.find(params[:id])
  end

  def edit
    @story = Story.find(params[:story_id])
    @contribution = Contribution.find(params[:id])
    @img_url = @contribution.image
  end

  def update
    @story = Story.find(params[:story_id])
    @contribution = Contribution.find(params[:id])
    @img_url = @contribution.image
    if @contribution.update(contribution_params)
      redirect_to story_contribution_path(@story, @contribution)
    else
      render :edit
    end
  end

  def destroy
    @story = Story.find(params[:story_id])
    @contribution = Contribution.find(params[:id])
    @contribution.destroy
    flash[:alert] = "Sentence Deleted Successfully!"
    redirect_to story_path(@story)
  end

private
  def contribution_params
    params.require(:contribution).permit(:image, :sentence, :user)
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  def index
    @stories = Story.all
  end

  def show
    @story = Story.find(params[:id])
  end

  def new
    @story = Story.new
  end

  def create
    @story = Story.new(story_params)
    if @story.save
      flash[:notice] = "Story successfully added!"
      redirect_to stories_path
    else
      render :new
    end
  end

  def edit
    @story = Story.find(params[:id])
  end

  def update
    @story = Story.find(params[:id])
    if @story.update(story_params)
      redirect_to stories_path
    else
      render :edit
    end
  end

  def destroy
    @story = Story.find(params[:id])
    @story.destroy
    flash[:alert] = "Story Deleted Successfully!"
    redirect_to stories_path
  end

private
  def story_params
    params.require(:story).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contributions/_form.html.erb
<%= render 'layouts/errors', :object => @contribution %>

<%= form_for [@story, @contribution] do |f| %>
  <%= f.hidden_field :image, :value => @img_url %>
  <%= f.label :sentence %>
  <%= f.text_field :sentence %>
  <%= f.label :user %>
  <%= f.text_field :user %>
  <%= f.submit  %>
<% end %>

app/views/contributions/edit.html.erb
<h1>Edit Contribution</h1>

<%= render "form" %>

app/views/contributions/new.html.erb
<h1>New contribution for <%= @story.name %></h1>

<%= image_tag @img_url %>
<br>
<%= link_to "Refresh Image", new_story_contribution_path(@story) %>
<hr>
<%= render 'form' %>

app/views/contributions/show.html.erb
<h3><%= @contribution.sentence %></h3>
<%= image_tag @contribution.image %>
<h5><em>by: <%= @contribution.user %></em></h5>

<p><%= link_to "Edit Sentence", edit_story_contribution_path(@story, @contribution) %></p>
<p><%= link_to "Delete Contribution", story_contribution_path(@story, @contribution),
                              :data => {:confirm => "You Sure?",
                                        :method => "delete"}%></p>

<p><%= link_to "Return to story", story_path(@story) %></p>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Oops there were some errors. Please try again:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StoryTime</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Permanent+Marker" rel="stylesheet">
  </head>

  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <a class="navbar-brand" href="/">Story Time</a>
      </div><!-- /.container-fluid -->
    </nav>
    <div class="notice">
      <%= flash[:notice] %>
    </div>
    <div class="warning">
      <%= flash[:alert] %>
    </div>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/stories/_form.html.erb
<%= render 'layouts/errors', :object => @story %>

<%= form_for @story do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit  %>
<% end %>

app/views/stories/edit.html.erb
<h1>Edit Story</h1>

<%= render "form" %>

app/views/stories/index.html.erb
<div class="jumbotron">
  <h1>Story Time</h1>
</div>

<% if @stories.any? %>
  <% @stories.each do |story| %>
  <h2 class="stories"><%= link_to story.name, story_path(story) %></h2>
  <% end %>
<% else %>
  <p>There are no stories yet! :(</p>
<% end %>

<hr>

<%= link_to "New Story", new_story_path %>

app/views/stories/new.html.erb
<h1>New Story</h1>

<%= render "form" %>

app/views/stories/show.html.erb
<h1><%= @story.name %></h1>

<br>
<% if @story.contributions.any? %>
  <div class="sentences">
    <% @story.contributions.each do |contribution| %>
      <%= link_to contribution.sentence, story_contribution_path(@story, contribution) %>
    <% end %>
  </div>
<% else %>
  <p>This story has no contributions yet! You should be the one to start the tale!</p>
<% end %>

<hr>
<p><%= link_to "Contribute to this story", new_story_contribution_path(@story) %></p>
<p><%= link_to "Return to stories", stories_path %></p>
<p><%= link_to "Edit Story", edit_story_path(@story) %></p>
<p><%= link_to "Delete Story", story_path(@story),
                              :data => {:confirm => "You Sure?",
                                        :method => "delete"}%></p>